### ISSUE TITLE
RCP call HMI TE2000  Engineering?

### ISSUE THREAD

**Issue by runtimevic** [Barteling/InvokingRpcMethodsDemo#2]
Hello, @Barteling :
Hello do you know if with RPC you could call a method of an FB from HMI TE2000 Engineering?
Best regards.

**Comment by Barteling** [comment]
It seems to be possible, 
Jack Borelius wrote something about that [here](https://www.linkedin.com/feed/update/urn:li:groupPost:1860933-6845825251444703232?commentUrn=urn%3Ali%3Acomment%3A%28groupPost%3A1860933-6845825251444703232%2C6845955995621961728%29&replyUrn=urn%3Ali%3Acomment%3A%28groupPost%3A1860933-6845825251444703232%2C6845988454233370624%29)
