### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by PeterZerlauth** [Barteling/InvokingRpcMethodsDemo#3]
![grafik](https://user-images.githubusercontent.com/48495545/174899332-2b0a7ed2-0642-4c47-84ea-9fd070bc2347.png)

I like your Solution, but i have still some trouble to find out how to get the Funktion Block path witch is in the Interface

**Comment by Barteling** [comment]
Hi Peter 
Could you be a bit more specific in what kind of troubles you have?

**Comment by PeterZerlauth** [comment]
1: Somehow i am not able to reed Propertys of a Funktion Block, i expected it to worke similar as a rpc method 
2: The XaeShell is able to resolve the FunctionBlock a connected interface, (iTest:= fbTest) ==> 'Main.fbTest' is connected to the interface, but it seems, ads C# is not supporting that

**Comment by Barteling** [comment]
I'm gonna need an example project to see what is going on, 
but if there really is an issue with twincat you can post it [here](https://github.com/Beckhoff/TF6000_ADS_DOTNET_V5_Samples)
